### PR TITLE
Fix Heroku deployment

### PR DESCRIPTION
**Pull request by hoangvanthien**
Solve #2 
Review: https://twitter.com/susi_tweetbot

### CODE REVIEW

**Comment by BrainBuzzer** [comment]
I don't think so there is any need to put node_modules folder in this. Add it in .gitignore

**Comment by hoangvanthien** [comment]
Please check again @BrainBuzzer.
After merging, `node_modules` will also be deleted.

**Comment by BrainBuzzer** [comment]
Sorry my bad. I saw that now.

**Comment by shivenmian** [comment]
Pretty good, thanks.

**Comment by shivenmian** [comment]
@mariobehling can you please merge this? I don't have write access to this repo. This PR is fine.

@hoangvanthien Well done, thanks :)

**Pull request merged**
