### PR TITLE
Fixes #8 i.e. Susi AI account replies to personal messages 

### LINKED ISSUE #8: Susi AI account on twitter doesn't reply to direct messages
Direct messages sent to SUSI AI account i.e. [SusiAI1](https://twitter.com/SusiAI1) on twitter.

Screenshots of the issue:
directreplytwitter

Would you like to work on this issue?
Yes.

### PR DESCRIPTION
**Pull request by Manveer695**
Fixes #8 i.e. SUSI AI account on twitter doesn't reply to private messages.

When a user personally messages to SUSI AI account [here](https://twitter.com/SusiAI1), after following the account, the account replies back:
twitterchat

When a person tweets like "@SusiAI1 universities in India", the answer is a table type output, which is more than 140 characters. So, in that case, the reply is sent as a personal message to the user who tweeted.
universitiesques
unians

### CODE REVIEW

**Comment by Manveer695** [comment]
@hoangvanthien @AliAyub007 @chashmeetsingh @madhavrathi @DravitLochan @jyoth1raditya Please review. Thank you.

**Review by madhavrathi — APPROVED** [review]
Please consider squashing your commits.

**Review by dynamitechetan — APPROVED** [review]

**Review by betterclever — APPROVED** [review]

**Review by chiragw15 — APPROVED** [review]

**Comment by Manveer695** [comment]
@mariobehling Can you please review and merge this pull request, so that I can make the next PR. Thank you so much.

**Review by AliAyub007 — APPROVED** [review]

**Comment by mariobehling** [comment]
Please include documentation for your PRs and always add relevant information into the Readme. How do people know how the bot works otherwise?

**Review by mariobehling — CHANGES_REQUESTED** [review]
Provide documentation as well!

**Comment by Manveer695** [comment]
Ok, sure @mariobehling sir. I raised previously a separate issue to update Readme i.e. #12. Updating it in this PR itself, hence closing that issue. Thank you for the review.

**Comment by mariobehling** [comment]
Good job. Keep it up!

**Pull request merged**
