### PR TITLE
Adding the retweet functionality

### PR DESCRIPTION
**Pull request by alejoheredia**
With this PR, the retweet functionality will be addet to the Susi Bot

### CODE REVIEW

**Comment by mariobehling** [comment]
I am unclear about this feature. Please open an issue and showcase what you would like to achieve. Thank you.

**Comment by alejoheredia** [comment]
@mariobehling I want the Bot to retweet tweets with the hashtags: #FOSSASIA, #SusiAI and #OpenSource

**Comment by alejoheredia** [comment]
@mariobehling It will retweet the most recent tweet which contains any on the hashtags above every 30 seconds

**Comment by alejoheredia** [comment]
@mariobehling What do you think?

**Comment by mariobehling** [comment]
I do not see how this is directly related to Susi AI. The goal of the tweetbot is to provide a conversation mode using twitter - just like the Susi Android app, but on twitter. A retweet project would be a completely different app and probably better suited to http://apps.loklak.org .

**Comment by alejoheredia** [comment]
@mariobehling But I think it would be a cool feature

**Comment by alejoheredia** [comment]
@mariobehling Because that way, the bot is interacting more

**Comment by mariobehling** [comment]
@Heredroky Sure, feel free to set it up on your repo. Would be a nice thing you can showcase. In regards to Susi AI here, it is not a retweet bot. Therefore closing it.

**Comment by alejoheredia** [comment]
@mariobehling 😞

**Pull request closed without merging**
