### PR TITLE
Made the Twitter Susi bot work again. 

### LINKED ISSUE #6: Susi tweetbot is not working.
susi_tweetbot is not working. 

I tried tweeting to it and got no replies, which can be seen here:
susi_tweetbotfinalpng

Would you like to work on this issue?
Yes.

### PR DESCRIPTION
**Pull request by Manveer695**
fixes #6 i.e. Susi tweetbot is not working.

Now Susi retweets to the messages tweeted mentioning it.

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please use a name with "tweetbot" inside. As the original URL is not available, check out e.g. http://susitweetbot.herokuapp.com/

**Comment by mariobehling** [comment]
Please help to make travis work in following PRs.

**Comment by Manveer695** [comment]
@mariobehling Yes sir, sure.

**Comment by hoangvanthien** [comment]
Nice work @Manveer695

**Pull request merged**
