### PR TITLE
Fixes #8 i.e. Susi AI account can replies to personal messages.

### LINKED ISSUE #8: Susi AI account on twitter doesn't reply to direct messages
Direct messages sent to SUSI AI account i.e. [SusiAI1](https://twitter.com/SusiAI1) on twitter.

Screenshots of the issue:
directreplytwitter

Would you like to work on this issue?
Yes.

### PR DESCRIPTION
**Pull request by Manveer695**
Fixes #8 i.e. SUSI AI account on twitter doesn't reply to private messages.

When a user personally messages to SUSI AI account [here](https://twitter.com/SusiAI1), after following the account, the account replies back:
twitterchat

When a person tweets like "@SusiAI1 universities in India", the answer is a table type output, which is more than 140 characters. So, in that case, the reply is sent as a personal message to the user who tweeted.
universitiesques
unians

### CODE REVIEW

**Comment by Manveer695** [comment]
@hoangvanthien @AliAyub007 @chashmeetsingh @madhavrathi @DravitLochan @jyoth1raditya 
Can anyone tell me, why my commits which were merged previously are shown again here? As we can see those got merged through [this](https://github.com/fossasia/susi_tweetbot/pull/7) pull request. So that I can resolve it. Thank you.

**Comment by chashmeetsingh** [comment]
@Manveer695 you will need to fetch and merge the changes from the master to you branch. basically you need to update your branch. You can try `git rebase master` and then force push to fix this.

**Comment by hoangvanthien** [comment]
It is because when the person who merged your #7 PR had squashed all your commits into one, resulting in difference in commit history between FOSSASIA's remote and your fork. Therefore when you make a new PR, it shows previous commits.

**Comment by Manveer695** [comment]
Sorry had some problems in this pull request. Closing it and will make a new pull request. Thanks!

**Pull request closed without merging**
